version: "3.3"

services:
  sqlite3_manga:
    container_name: sqlite3_manga
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      #Modify following line
      - ./db/:/root/db/
    restart: unless-stopped

  back_manga:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic
      --no-input && gunicorn -b 0.0.0.0:8919 MangaProject.wsgi --reload"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./static:/static
    ports:
      - "8919:8919"
    depends_on:
      - sqlite3_manga
    links:
      - sqlite3_manga